title: Agora Wiki
description: Agora Nomic's wiki. Learn more at https://www.agoranomic.org/.
show_downloads: true
git_branch: master
logo_url: https://avatars1.githubusercontent.com/u/28770272?v=3&s=200
google_analytics:
theme: 
use_github_wiki: false
use_prose_io: true
google_cse_token: 
custom_head: false
custom_sidebar: false
custom_footer: false
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
